# Generated by Django 4.1.3 on 2022-12-28 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('airport_ID', models.AutoField(primary_key=True, serialize=False)),
                ('airport_Name', models.CharField(default='Hazrat Shahjalal International Airport', max_length=40)),
                ('area', models.CharField(default='Dhaka', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_ID', models.CharField(default='B8700', max_length=10)),
                ('departure_Time', models.TimeField()),
                ('landing_Time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FlightInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_Image', models.ImageField(upload_to='Airlines/Images')),
                ('flight_ID', models.CharField(default='B8700', max_length=10)),
                ('flight_Name', models.CharField(max_length=40)),
                ('flight_Class', models.CharField(default='Economy', max_length=10)),
                ('flight_Price', models.FloatField()),
                ('departure_Place', models.CharField(default='Dhaka', max_length=40)),
                ('destination', models.CharField(max_length=40)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.airport')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.schedule')),
            ],
        ),
    ]
