# Generated by Django 4.1.3 on 2022-12-28 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_remove_flightinfo_fk_flightinfo_airport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('customer_ID', models.AutoField(primary_key=True, serialize=False)),
                ('customer_Name', models.CharField(max_length=40)),
                ('customer_Email', models.EmailField(max_length=254)),
                ('customer_Address', models.TextField()),
                ('flight_Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.flightinfo')),
            ],
        ),
    ]
