# Generated by Django 4.1.3 on 2023-01-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='flight_Name',
        ),
        migrations.AddField(
            model_name='purchase',
            name='customer_Phone',
            field=models.CharField(default='+880', max_length=14),
        ),
    ]
